# Generated by Django 5.2.15 on 2026-06-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banner/"),
        ),
    ]
