# Generated by Django 5.2.15 on 2026-06-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_userpreference_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="quote",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
