# Generated by Django 5.2.15 on 2026-06-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_userpreference_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="kind",
            field=models.CharField(
                choices=[("strength", "Strength"), ("cardio", "Cardio")],
                default="strength",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="workoutlog",
            name="distance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="workoutlog",
            name="distance_unit",
            field=models.CharField(
                blank=True,
                choices=[("km", "km"), ("mi", "mile")],
                default="km",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="workoutlog",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
